### PR TITLE
Display on Pre3 is normally sized

### PR DESCRIPTION
**Pull request by DougReeder**
Also allows the app to be found in Universal Search under the term "alert"

### CODE REVIEW

**Comment by GeorgeMari** [comment]
Hi Doug - thanks for the pull request.  I'll try it out later this evening or later this weekend.

**Comment by DougReeder** [comment]
You�re probably on this, but if you configure two locations, dashboards appear for both, but alerts for the second do not appear in the main listing. 

On May 7, 2015, at 8:23 AM, George Mari notifications@github.com wrote:

> Hi Doug - thanks for the pull request. I'll try it out later this evening or later this weekend.
> 
> �
> Reply to this email directly or view it on GitHub.

Doug Reeder
reeder.29@gmail.com
https://ello.co/dougreeder
https://twitter.com/reeder29
http://reeder29.livejournal.com/

http://hominidsoftware.com

**Comment by GeorgeMari** [comment]
The only time I've seen this happen is the following scenario:
1. Notification gets displayed for a new alert.
2. Several minutes or hours go by, and the NWS expires the alert.
3. You open the app, and no alert is displayed, because it no longer is active.  But the notification is still sitting at the bottom of the screen.

If you think this isn't what likely happened to you, let me know.

**Comment by DougReeder** [comment]
That could be what I saw.It's still an unfortunate user experience - if there's a dashboard, the app should be able to display the alert in full.-- Sent from my HP Pre3 running webOSOn May 10, 2015 10:36 PM, George Mari notifications@github.com wrote: The only time I've seen this happen is the following scenario:

Notification gets displayed for a new alert.
Several minutes or hours go by, and the NWS expires the alert.
You open the app, and no alert is displayed, because it no longer is active.  But the notification is still sitting at the bottom of the screen.

If you think this isn't what likely happened to you, let me know.

**Comment by GeorgeMari** [comment]
Doug, you seem like you probably know more about git than I do.  :-)  I'd like to merge your pull request, but not to the master branch.  I've created a 021 branch for the my next planned release, and I'd like to merge to that branch.  Then once I have everything else I'm planning for in 021, I'll merge that branch to master.  Does that make sense?  

If so, any advice on how to merge your pull request to the 021 branch?  If I understand correctly, if I just merged it now through the github front end, it would merge to master.

Thanks.

**Comment by DougReeder** [comment]
I'm a bit weak on merging different branches, so I'm not clear on why you're doing it that way. When I compare my fork's master branch with your forks's 021 branch, GitHub says there's no difference. When I look at the files in your 021 branch, they appear to contain the changes in my PR. So it looks like there's nothing you need do. I'll close the PR.-- Sent from my HP Pre3 running webOSOn May 12, 2015 10:10 PM, George Mari notifications@github.com wrote: Doug, you seem like you probably know more about git than I do.  :-)  I'd like to merge your pull request, but not to the master branch.  I've created a 021 branch for the my next planned release, and I'd like to merge to that branch.  Then once I have everything else I'm planning for in 021, I'll merge that branch to master.  Does that make sense?  

If so, any advice on how to merge your pull request to the 021 branch?  If I understand correctly, if I just merged it now through the github front end, it would merge to master.

Thanks.

**Pull request closed without merging**
